name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git python3-pip openjdk-11-jdk unzip zip wget ant
        pip3 install --upgrade pip
        pip3 install cython==0.29.36
        pip3 install --no-cache-dir buildozer

    - name: Install Android SDK
      run: |
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools latest
        
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/latest/bin:$PATH
        
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34" "ndk;23.1.7779620"

    - name: Build APK with Buildozer
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/23.1.7779620
        export PATH=$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/34.0.0:$PATH
        
        pip3 install -U buildozer
        buildozer init
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyAssistant-apk
        path: bin/*.apk
